/*
DBS211NEE - Final Project MS3 - Data Script
Song Hwan Oh / 116872227 
Sangjune Lee / 123050221 
Ji Ho Nam / 139817217 
Shine Lee / 130563224 
August 4, 2023
*/

/*
providing the scripting to insert sample data into all tables.  
The amount of data should be enough to allow addiquate testing of an application build upon the designed database.  
Rule of Thumb: 20-30 rows per data tables and their associated bridge tables, and an appropriate number of rows in lookup tables.
*/
-- xCOUNTRY Table
INSERT ALL
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('USA', 'North America', 'Washington, D.C.', 10, 'A')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Brazil', 'South America', 'Brasília', 5, 'B')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Germany', 'Europe', 'Berlin', 7, 'C')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('France', 'Europe', 'Paris', 8, 'D')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Argentina', 'South America', 'Buenos Aires', 6, 'E')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Spain', 'Europe', 'Madrid', 9, 'F')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Italy', 'Europe', 'Rome', 12, 'G')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('England', 'Europe', 'London', 11, 'H')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Netherlands', 'Europe', 'Amsterdam', 14, 'A')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Mexico', 'North America', 'Mexico City', 15, 'B')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Portugal', 'Europe', 'Lisbon', 18, 'C')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Chile', 'South America', 'Santiago', 20, 'D')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Belgium', 'Europe', 'Brussels', 16, 'E')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Uruguay', 'South America', 'Montevideo', 22, 'F')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Colombia', 'South America', 'Bogotá', 17, 'G')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Croatia', 'Europe', 'Zagreb', 19, 'H')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Russia', 'Europe', 'Moscow', 23, 'A')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Ghana', 'Africa', 'Accra', 28, 'B')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Japan', 'Asia', 'Tokyo', 27, 'C')
    INTO xCOUNTRY (countryName, continent, capitalCity, FIFARanking, groupName) VALUES ('Australia', 'Oceania', 'Canberra', 31, 'D')
SELECT * FROM DUAL;

-- xPERSON Table
INSERT ALL
    INTO xPERSON (firstName, lastName, DOB) VALUES ('John', 'Doe', TO_DATE('1990-05-15', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Jane', 'Smith', TO_DATE('1985-08-20', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Michael', 'Johnson', TO_DATE('1993-02-10', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Emily', 'Brown', TO_DATE('1992-11-30', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('David', 'Williams', TO_DATE('1988-04-25', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Sophia', 'Miller', TO_DATE('1995-07-08', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('James', 'Jones', TO_DATE('1987-01-12', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Olivia', 'Davis', TO_DATE('1991-09-18', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Daniel', 'Wilson', TO_DATE('1989-03-22', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Ava', 'Taylor', TO_DATE('1994-06-05', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('William', 'Evans', TO_DATE('1998-10-01', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Mia', 'Thomas', TO_DATE('1997-12-14', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Joseph', 'Martinez', TO_DATE('1996-02-28', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Emma', 'Hernandez', TO_DATE('1999-04-11', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Alexander', 'Lopez', TO_DATE('1991-07-23', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Sofia', 'Garcia', TO_DATE('1993-09-09', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Michael', 'Rivera', TO_DATE('1990-11-05', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Isabella', 'Lee', TO_DATE('1992-01-19', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Ethan', 'Rodriguez', TO_DATE('1988-03-27', 'YYYY-MM-DD'))
    INTO xPERSON (firstName, lastName, DOB) VALUES ('Amelia', 'Perez', TO_DATE('1987-06-30', 'YYYY-MM-DD'))
SELECT * FROM DUAL;

-- xPLAYER Table
INSERT ALL
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (7, 'FW', 180, 75, 'FC Barcelona', 'L', 1)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (10, 'MF', 175, 68, 'Real Madrid', 'R', 2)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (5, 'DF', 190, 85, 'Bayern Munich', 'R', 3)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (20, 'FW', 178, 72, 'Paris Saint-Germain', 'L', 4)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (8, 'MF', 182, 78, 'Manchester City', 'R', 5)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (3, 'DF', 186, 83, 'Liverpool', 'R', 6)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (11, 'FW', 183, 77, 'AC Milan', 'R', 7)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (4, 'MF', 177, 70, 'Chelsea', 'L', 8)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (6, 'DF', 191, 88, 'Ajax', 'R', 9)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (9, 'FW', 179, 74, 'Club América', 'L', 10)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (2, 'MF', 176, 71, 'Sporting CP', 'R', 11)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (18, 'DF', 184, 80, 'Colo-Colo', 'L', 12)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (14, 'FW', 181, 76, 'Anderlecht', 'R', 13)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (17, 'MF', 180, 73, 'Peñarol', 'R', 14)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (22, 'DF', 183, 79, 'Atletico Nacional', 'L', 15)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (16, 'FW', 177, 75, 'Deportivo Cali', 'R', 16)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (13, 'MF', 179, 72, 'Dinamo Zagreb', 'L', 17)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (19, 'DF', 182, 78, 'Lokomotiv Moscow', 'R', 18)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (23, 'FW', 185, 82, 'Hearts of Oak', 'L', 19)
    INTO xPLAYER (shirtNumber, fPosition, height, weight, clubTeam, dominantFoot, countryID) VALUES (15, 'MF', 176, 70, 'Kashima Antlers', 'R', 20)
SELECT * FROM DUAL;

-- xUSERS Table
INSERT ALL
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('john@example.com', 1, 'EN', 'JDoe')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('jane@example.com', 2, 'EN', 'JSmith')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('michael@example.com', 3, 'EN', 'MJohnson')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('emily@example.com', 4, 'EN', 'EBrown')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('david@example.com', 5, 'EN', 'DWilliams')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('sophia@example.com', 6, 'EN', 'SMiller')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('james@example.com', 7, 'EN', 'JJones')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('olivia@example.com', 8, 'EN', 'ODavis')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('daniel@example.com', 9, 'EN', 'DWilson')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('ava@example.com', 10, 'EN', 'ATaylor')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('william@example.com', 11, 'EN', 'WEvans')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('mia@example.com', 12, 'EN', 'MThomas')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('joseph@example.com', 13, 'EN', 'JMartinez')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('emma@example.com', 14, 'EN', 'EHernandez')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('alexander@example.com', 15, 'EN', 'ALopez')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('sofia@example.com', 16, 'EN', 'SGarcia')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('michael2@example.com', 17, 'EN', 'MRivera')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('isabella@example.com', 18, 'EN', 'ILee')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('ethan@example.com', 19, 'EN', 'ERodriguez')
    INTO xUSERS (email, countryResidence, prefLanguage, nickName) VALUES ('amelia@example.com', 20, 'EN', 'APerez')
SELECT * FROM DUAL;

-- xVENUE Table
INSERT ALL
    INTO xVENUE (venueName, city, vCapacity) VALUES ('MetLife Stadium', 'East Rutherford', 82500)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('Rose Bowl', 'Pasadena', 90000)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('AT&T Stadium', 'Arlington', 80000)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('Gillette Stadium', 'Foxborough', 68756)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('Soldier Field', 'Chicago', 61500)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('Mercedes-Benz Superdome', 'New Orleans', 73208)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('Arrowhead Stadium', 'Kansas City', 76416)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('Empower Field at Mile High', 'Denver', 76125)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('CenturyLink Field', 'Seattle', 69000)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('Nissan Stadium', 'Nashville', 69274)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('Lincoln Financial Field', 'Philadelphia', 69029)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('Levi''s Stadium', 'Santa Clara', 68500)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('FedExField', 'Landover', 82000)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('Hard Rock Stadium', 'Miami Gardens', 64767)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('Bills Stadium', 'Orchard Park', 71608)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('FirstEnergy Stadium', 'Cleveland', 67895)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('M&T Bank Stadium', 'Baltimore', 71008)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('Paul Brown Stadium', 'Cincinnati', 65515)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('U.S. Bank Stadium', 'Minneapolis', 66655)
    INTO xVENUE (venueName, city, vCapacity) VALUES ('State Farm Stadium', 'Glendale', 63400)
SELECT * FROM DUAL;

-- xMATCH_TYPE Table
INSERT ALL
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('F', 'Friendly')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('C', 'Championship')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('L', 'League')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('C', 'Cup')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('E', 'Exhibition')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('Q', 'Qualification')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('S', 'Semifinal')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('F', 'Final')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('P', 'Playoff')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('A', 'All-Star')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('T', 'Tournament')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('M', 'Match')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('R', 'Round')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('G', 'Group')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('D', 'Division')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('B', 'Bracket')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('H', 'Home/Away')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('E', 'Elimination')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('I', 'International')
    INTO xMATCH_TYPE (matchType, matchTypeDesc) VALUES ('N', 'National')
SELECT * FROM DUAL;

-- xEVENTS_DESC Table
INSERT ALL
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('G', 'Goal')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('YC', 'Yellow Card')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('RC', 'Red Card')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('S', 'Substitution')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('P', 'Penalty')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('F', 'Foul')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('O', 'Offside')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('C', 'Corner')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('T', 'Throw-in')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('I', 'Injury')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('A', 'Assist')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('M', 'Missed Shot')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('D', 'Dribble')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('N', 'Nutmeg')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('R', 'Rebound')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('H', 'Header')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('V', 'Save')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('K', 'Block')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('U', 'Substitution Cancel')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('E', 'Extra Time Start')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('Z', 'End of Extra Time')
    INTO xEVENTS_DESC (eventType, eventDesc) VALUES ('W', 'End of Match')
SELECT * FROM DUAL;

-- xMATCH Table
INSERT ALL
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (1, 2, TO_DATE('2023-08-10 15:00', 'YYYY-MM-DD HH24:MI'), 1, 'F', 2, 1)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (2, 3, TO_DATE('2023-08-11 14:30', 'YYYY-MM-DD HH24:MI'), 2, 'C', 1, 3)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (1, 3, TO_DATE('2023-08-12 16:15', 'YYYY-MM-DD HH24:MI'), 3, 'C', 0, 0)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (4, 5, TO_DATE('2023-08-13 18:30', 'YYYY-MM-DD HH24:MI'), 4, 'L', 2, 2)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (6, 7, TO_DATE('2023-08-14 20:45', 'YYYY-MM-DD HH24:MI'), 5, 'C', 3, 1)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (8, 9, TO_DATE('2023-08-15 12:00', 'YYYY-MM-DD HH24:MI'), 6, 'F', 1, 0)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (10, 11, TO_DATE('2023-08-16 17:15', 'YYYY-MM-DD HH24:MI'), 7, 'C', 2, 2)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (12, 13, TO_DATE('2023-08-17 19:30', 'YYYY-MM-DD HH24:MI'), 8, 'L', 1, 2)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (14, 15, TO_DATE('2023-08-18 14:00', 'YYYY-MM-DD HH24:MI'), 9, 'F', 0, 1)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (16, 17, TO_DATE('2023-08-19 16:45', 'YYYY-MM-DD HH24:MI'), 10, 'C', 3, 3)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (18, 19, TO_DATE('2023-08-20 18:30', 'YYYY-MM-DD HH24:MI'), 11, 'L', 1, 0)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (20, 1, TO_DATE('2023-08-21 20:15', 'YYYY-MM-DD HH24:MI'), 12, 'C', 2, 2)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (2, 3, TO_DATE('2023-08-22 15:30', 'YYYY-MM-DD HH24:MI'), 13, 'F', 0, 1)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (4, 5, TO_DATE('2023-08-23 17:45', 'YYYY-MM-DD HH24:MI'), 14, 'C', 2, 3)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (6, 7, TO_DATE('2023-08-24 19:00', 'YYYY-MM-DD HH24:MI'), 15, 'L', 3, 1)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (8, 9, TO_DATE('2023-08-25 13:15', 'YYYY-MM-DD HH24:MI'), 16, 'C', 1, 1)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (10, 11, TO_DATE('2023-08-26 16:30', 'YYYY-MM-DD HH24:MI'), 17, 'F', 2, 0)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (12, 13, TO_DATE('2023-08-27 18:45', 'YYYY-MM-DD HH24:MI'), 18, 'C', 0, 2)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (14, 15, TO_DATE('2023-08-28 21:00', 'YYYY-MM-DD HH24:MI'), 19, 'L', 1, 1)
    INTO xMATCH (countryID_A, countryID_B, dateNTime, venueID, matchType, a_score, b_score) VALUES (16, 17, TO_DATE('2023-08-29 14:15', 'YYYY-MM-DD HH24:MI'), 20, 'C', 2, 3)
SELECT * FROM DUAL;

-- xEVENTS Table
INSERT ALL
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (1, 'G', 1, 23, 2)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (1, 'YC', 2, 45, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (2, 'G', 3, 60, 3)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (2, 'RC', 4, 75, 1)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (3, 'G', 5, 30, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (3, 'G', 6, 65, 4)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (4, 'G', 7, 15, 1)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (4, 'YC', 8, 60, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (5, 'G', 9, 42, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (5, 'G', 10, 68, 3)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (6, 'G', 11, 81, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (6, 'YC', 12, 20, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (7, 'G', 13, 50, 2)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (7, 'RC', 14, 76, 1)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (8, 'G', 15, 37, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (8, 'G', 16, 85, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (9, 'G', 17, 12, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (9, 'G', 18, 73, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (10, 'G', 19, 64, 2)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (10, 'YC', 20, 30, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (11, 'G', 1, 22, 1)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (11, 'RC', 2, 56, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (12, 'G', 3, 75, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (12, 'G', 4, 90, 2)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (13, 'G', 5, 41, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (13, 'G', 6, 69, 1)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (14, 'G', 7, 53, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (14, 'YC', 8, 78, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (15, 'G', 9, 28, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (15, 'G', 10, 60, 3)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (16, 'G', 11, 72, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (16, 'YC', 12, 15, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (17, 'G', 13, 49, 2)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (17, 'RC', 14, 71, 1)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (18, 'G', 15, 36, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (18, 'G', 16, 88, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (19, 'G', 17, 19, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (19, 'G', 18, 82, 0)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (20, 'G', 19, 62, 2)
    INTO xEVENTS (matchID, eventType, playerID, regularTime, adittionalTime) VALUES (20, 'YC', 20, 25, 0)
SELECT * FROM DUAL;

-- xFAVORITES_SETTING Table
INSERT ALL
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (2, 2, '1')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (2, 4, '0')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (2, 6, '1')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (3, 5, '0')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (3, 7, '1')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (3, 9, '1')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (4, 6, '0')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (4, 8, '1')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (4, 10, '0')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (5, 9, '1')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (5, 11, '0')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (5, 13, '0')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (6, 12, '1')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (6, 14, '0')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (6, 16, '1')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (7, 15, '0')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (7, 17, '1')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (7, 19, '1')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (8, 18, '0')
    INTO xFAVORITES_SETTING (userID, favoriteMatchID, notify) VALUES (8, 20, '1')
SELECT * FROM DUAL;
