/*
DBS211NEE - Final Project MS3 - Creation Script
Song Hwan Oh / 116872227 
Sangjune Lee / 123050221 
Ji Ho Nam / 139817217 
Shine Lee / 130563224 
August 4, 2023
*/

/*
providing the scripting to create all the tables, including all constraints and features as designed in the ERD and data dictionary.
*/

CREATE TABLE COUNTRY 
(
  countryID     NUMBER(4)   GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  countryName   VARCHAR(3)  NOT NULL, 
  continent     VARCHAR(10), 
  capitalCity   VARCHAR(30), 
  FIFARanking   NUMBER(3)   NOT NULL, 
  groupName     VARCHAR(1)  NOT NULL 
);

CREATE TABLE PERSON 
(
  personID  NUMBER(4)   GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  firstName VARCHAR(40) NOT NULL, 
  LASTNAME  VARCHAR(40) NOT NULL, 
  DOB       DATE 
);

CREATE TABLE PLAYER (
    playerID        NUMBER(4)       GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    shirtNumber     NUMBER(2)       CHECK (shirtNumber BETWEEN 1 AND 99),
    fPosition       VARCHAR2(2),
    height          NUMBER(3)       CHECK (height BETWEEN 1 AND 250),
    weight          NUMBER(3)       CHECK (weight BETWEEN 1 AND 250),
    clubTeam        VARCHAR2(50),
    dominantFoot    VARCHAR2(1)     CHECK (dominantFoot IN ('L', 'R')),
    countryID       NUMBER(4)       NOT NULL CHECK (countryID BETWEEN 1 AND 9999),
    CONSTRAINT fk_country FOREIGN KEY (countryID) REFERENCES COUNTRY(countryID) 
);

CREATE TABLE USERS (
    userID              NUMBER(4)       GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    email               VARCHAR2(50)    UNIQUE NOT NULL,
    countryResidence    VARCHAR2(3),
    prefLanguage        VARCHAR2(2)     DEFAULT 'EN' NOT NULL,
    nickName            VARCHAR2(20)    UNIQUE,
    
    CONSTRAINT chk_countryResidence CHECK (countryResidence IN ('USA')), — You can add more country codes as needed
    CONSTRAINT chk_userID_ra